# starship.toml

add_newline = false
palette = "default"

format = """
[â•­](fg:separator)\
$status\
$username$env_var\
$directory\
$git_branch$git_status\
$cmd_duration\
$line_break\
[â•°](fg:separator)\
$character\
"""

###########################################

[palettes.default]
prompt_ok = "#8047c1"
prompt_err = "#ff0000"
icon = "#161514"
separator = "#35312c"
background = "#35312c"

directory = "#0CC40F"
username = "#5f00ff"
git_info = "#ff6a00"
duration = "#eeff00"
status = "#ff0000"

###########################################

[env_var.UNAME]
format = "[@$env_value ](bg:background)[î‚´](fg:background)"

[username]
show_always = true
format = "[â”€](fg:separator)[î‚¶](fg:username)[ğŸ« ](fg:icon bg:username)[î‚´](fg:username bg:background)[ $user](bg:background)[î‚´](fg:background)"


[character]
success_symbol = "[â¯](fg:prompt_ok)"
error_symbol = "[â¯](fg:prompt_err)"

[directory]
truncation_symbol = "../"
truncation_length = 3
format = "[â”€](fg:separator)[î‚¶](fg:directory)[ï»](fg:icon bg:directory)[î‚´](fg:directory bg:background)[ $path](bg:background)[î‚´](fg:background)"

[git_branch]
symbol = "îœ¥ "
format = "[â”€](fg:separator)[î‚¶](fg:git_info)[îœ¥](fg:icon bg:git_info)[î‚´](fg:git_info bg:background)[ $branch](bg:background)"

[git_status]
format = "[ $all_status$ahead_behind ](bg:background)[î‚´](fg:background)"

[status]
format = "[â”€](fg:separator)[î‚¶](fg:status)[î½¶](fg:icon bg:status)[î‚´](fg:status bg:background)[ $status](bg:background)[î‚´](fg:background)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[â”€](fg:separator)[î‚¶](fg:status)[î½¶](fg:icon bg:status)[î‚´](fg:status bg:background)[ $pipestatus](bg:background)[î‚´](fg:background)"
disabled = false

[cmd_duration]
format = "[â”€](fg:separator)[î‚¶](fg:duration)[ó±‹](fg:icon bg:duration)[î‚´](fg:duration bg:background)[ $duration](bg:background)[î‚´](fg:background)"
min_time = 1000

[time]
format = "[î‚¶](fg:duration)[ó°¥”](fg:icon bg:duration)[î‚´](fg:duration bg:background)[ $time](bg:background)[î‚´](fg:background)"
disabled = false
